{
 "title": "TFM MongoDB",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Mongo Member Downtime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(name)(mongodb_replset_member_downtime_total)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Dummy service request/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(service)(irate(dummy_service_requests_total[15s]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "MongoDB member Health",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(name)(mongodb_replset_member_health)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Dummy service request stored / sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(service)(irate(dummy_service_requests_stored_total[5m]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Dummy service  Requests duration Seconds",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(dummy_service_request_duration_seconds{quantile=\"0.95\"})",
     "legendFormat": "95 percentile"
    },
    {
     "expr": "avg(dummy_service_request_duration_seconds{quantile=\"0.99\"})",
     "legendFormat": "99 percentile"
    }
   ]
  },
  {
   "title": "Dummy service  failed / sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(service)(irate(dummy_service_requests_error_storing_total[5m]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Dummy service concurrent requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(dummy_service_concurrent_requests) ",
     "legendFormat": "req/s"
    }
   ]
  }
 ]
}