apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: dummy-service-cert
  namespace: tfm
spec:
  commonName: mca.ethcero.es
  dnsNames:
  - mca.ethcero.es
  secretName: dummy-service-tls-secret
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
