---

apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: mongo
spec:
  members: 3
  type: ReplicaSet
#  version: "4.2.6"
  version: "4.4.1"
  featureCompatibilityVersion: "4.2"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: my-user
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: my-user-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
        - name: readWriteAnyDatabase
          db: admin
  statefulSet:
      spec:
        template:
          spec:
            containers:
              - name: "mongodb-agent"
                resources:
                  requests:
                    cpu: 100m
                    memory: 200M
              - name: "mongod"
                resources:
                  requests:
                    cpu: 100m
                    memory: 200M

# the user credentials will be generated from this secret
# once the credentials are generated, this secret is no longer required
---
apiVersion: v1
kind: Secret
metadata:
  name: my-user-password
type: Opaque
stringData:
  password: test